# Generated by Django 4.0.5 on 2022-06-16 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutrition', '0002_product_image_alter_product_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Комментарий')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Запись создана')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Страна производства')),
            ],
            options={
                'verbose_name': 'Страна производства',
                'verbose_name_plural': 'Страны производства',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='maker',
            options={'ordering': ['name'], 'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-create_at'], 'verbose_name': 'Спортпит', 'verbose_name_plural': 'Спортпит'},
        ),
        migrations.AddField(
            model_name='product',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(db_index=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Запись создана'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutrition.maker', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='maker',
            index=models.Index(fields=['name'], name='nutrition_m_name_579c5b_idx'),
        ),
        migrations.AddIndex(
            model_name='maker',
            index=models.Index(fields=['country'], name='nutrition_m_country_fb11d7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='nutrition_p_name_66f4cc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='nutrition_p_price_bb6a8d_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='product_price_gte_0'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['name'], name='nutrition_c_name_6519dc_idx'),
        ),
        migrations.AddField(
            model_name='comment',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutrition.maker', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutrition.product', verbose_name='Спортпит'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='maker',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutrition.country', verbose_name='Страна производства'),
        ),
    ]
