# Generated by Django 4.0.5 on 2022-06-17 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutrition', '0007_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (None, 'Ваша оценка')], verbose_name='Оценка пользователя')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Дата оценки')),
                ('maker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutrition.maker', verbose_name='Производитель спортпита')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutrition.product', verbose_name='Спортпит')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
                'ordering': ['-create_at'],
            },
        ),
    ]
