# Generated by Django 4.0.5 on 2022-06-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0008_ratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
