# Generated by Django 4.0.5 on 2022-06-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_securecode_options_securecode_time_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securecode',
            name='time_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
