# Generated by Django 4.0.5 on 2022-07-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0003_alter_usermessage_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='read',
            field=models.BooleanField(auto_created=True, default=False, verbose_name='Прочитано'),
        ),
    ]
