# Generated by Django 4.0.5 on 2022-06-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата тренировки')),
                ('content', models.JSONField(verbose_name='Содержание тренировки')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
