# Generated by Django 4.0.5 on 2022-06-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='content',
            field=models.JSONField(blank=True, verbose_name='Содержание тренировки'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(auto_now_add=True, unique=True, verbose_name='Дата тренировки'),
        ),
    ]
