# Generated by Django 4.0.5 on 2022-06-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_alter_workout_content_alter_workout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='content',
            field=models.JSONField(blank=True, null=True, verbose_name='Содержание тренировки'),
        ),
    ]
