# Generated by Django 4.0.5 on 2022-06-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_alter_workout_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
