# Generated by Django 4.0.5 on 2022-06-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_alter_workout_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
