# Generated by Django 4.0.5 on 2022-06-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_alter_workout_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата тренировки'),
        ),
    ]
