# Generated by Django 4.0.5 on 2022-06-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_alter_workout_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='user_id',
            new_name='telegram_id',
        ),
    ]
